# Generated by Django 4.0.6 on 2022-07-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('chapter_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chapter_name', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('chapter_desc', models.CharField(max_length=300)),
                ('pub_date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='images')),
                ('yt_link', models.URLField(default='https://www.youtube.com/c/AnjeshNITJ', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Chemistry',
            fields=[
                ('chemistry_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('main_heading', models.CharField(max_length=50)),
                ('sub_heading', models.CharField(max_length=50)),
                ('link_specifier_1', models.CharField(default='', max_length=50)),
                ('first_link', models.URLField(default='https://www.youtube.com/c/AnjeshNITJ', max_length=150)),
                ('link_specifier_2', models.CharField(default='', max_length=50)),
                ('second_link', models.URLField(default='https://www.youtube.com/c/AnjeshNITJ', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('contact_desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('main_heading', models.CharField(max_length=50)),
                ('sub_heading', models.CharField(max_length=50)),
                ('link_specifier_1', models.CharField(default='', max_length=50)),
                ('first_link', models.URLField(default='https://www.youtube.com/c/AnjeshNITJ', max_length=150)),
                ('link_specifier_2', models.CharField(default='', max_length=50)),
                ('second_link', models.URLField(default='https://www.youtube.com/c/AnjeshNITJ', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Mathematics',
            fields=[
                ('maths_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('main_heading', models.CharField(max_length=50)),
                ('sub_heading', models.CharField(max_length=50)),
                ('link_specifier_1', models.CharField(default='', max_length=50)),
                ('first_link', models.URLField(default='https://www.youtube.com/c/AnjeshNITJ', max_length=150)),
                ('link_specifier_2', models.CharField(default='', max_length=50)),
                ('second_link', models.URLField(default='https://www.youtube.com/c/AnjeshNITJ', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Physics',
            fields=[
                ('physics_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('main_heading', models.CharField(max_length=50)),
                ('sub_heading', models.CharField(max_length=50)),
                ('link_specifier_1', models.CharField(default='', max_length=50)),
                ('first_link', models.URLField(default='https://www.youtube.com/c/AnjeshNITJ', max_length=150)),
                ('link_specifier_2', models.CharField(default='', max_length=50)),
                ('second_link', models.URLField(default='https://www.youtube.com/c/AnjeshNITJ', max_length=150)),
            ],
        ),
    ]
